#---------------#
# Site settings #
#---------------#

url: http://unac-estadistica.github.io
title: Estadística para Contaduría
subtitle: Corporación Universitaria Adventista de Colombia
simple_search: https://www.google.com/search
description: Guía del curso de Estadística
baseurl: ""
permalink: /:categories/:title/
